### ISSUE TITLE
Obfuscate your API Key

### ISSUE THREAD

**Issue by SlayterDev** [richardxyx/Forecast#1]
It looks like this service charges after a certain number of API calls. I'd hate to see you go broke because someone grabbed the source and started spamming it. Just a heads up.

**Comment by richardneitzke** [comment]
Thanks for noticing! I already thought of this, but the service will just stop working after the API calls are spent. Generating a new key is just one klick and I'll add a comment that asks for using your own key, as it is easy to obtain.
